### ISSUE TITLE
🐛 Dev command fails to start compiled app

### ISSUE THREAD

**Issue by codemicro** [gofiber/fiber-cli#11]
When using the `fiber dev` command, the binary appears to be destroyed before it can be run.

![image](https://user-images.githubusercontent.com/25284325/96156176-b2de4c00-0f08-11eb-8679-3e367347ac92.png)

The project in question is an unmodified one generated by the CLI.

**System**: Windows 10, Go 1.15.2, fiber-cli v0.0.1

**Comment by kiyonlin** [comment]
`v0.0.2` is released too, please try it!

**Comment by codemicro** [comment]
Looks good, it now works. For some reason, running `go get -u -v github.com/gofiber/fiber-cli` wasn't updating the CLI, but building it manually worked.
